"""Generate a runnable Python reproducer (spec section 35).

The generated script matches the engine that actually ran:

* ``json_api``      → httpx + pagination loop
* ``table``         → httpx + pandas.read_html
* ``repeated_dom``  → httpx + lxml selectors
* ``direct_file``   → httpx + the matching pandas reader
* ``article``       → httpx + trafilatura
* ``playwright``    → Playwright script
* ``crawl4ai``      → Crawl4AI script

Credentials are never embedded; the script reads them from environment
variables.
"""

from __future__ import annotations

from typing import Any

HEADER = '''"""Reproduction script generated by Smart Research Web Scraper {version}.

Developed by Dr Merwan Roudane (https://github.com/merwanroudane).

Source:  {url}
Engine:  {engine}
Created: {created}

Dependencies:
    pip install {deps}

Any credentials are read from environment variables; none are stored in this file.
"""

from __future__ import annotations
{stdlib_imports}
'''


def _insert_rate_limit(body: str, delay: float) -> str:
    """Place the delay constant after the body imports so the script stays PEP 8."""
    line = f"REQUEST_DELAY_SECONDS = {delay}  # be polite to the source"
    lines = body.splitlines()
    last_import = -1
    for index, text in enumerate(lines[:20]):
        if text.startswith(("import ", "from ")):
            last_import = index
    if last_import < 0:
        return f"{line}\n\n{body}"
    lines.insert(last_import + 1, "\n" + line)
    return "\n".join(lines)


def generate(
    *,
    engine: str,
    url: str,
    recipe: dict[str, Any],
    columns: list[str] | None = None,
    version: str = "0.1.0",
    created: str = "",
) -> str:
    """Return the full Python source of the reproducer."""
    dataset = recipe.get("dataset", {}) or {}
    pagination = recipe.get("pagination", {}) or {}
    limits = recipe.get("limits", {}) or {}
    max_pages = int(limits.get("max_pages", 1) or 1)
    delay = 0.7

    builders = {
        "json_api": _json_api_script,
        "table": _table_script,
        "repeated_dom": _repeated_script,
        "direct_file": _file_script,
        "article": _article_script,
        "feed": _feed_script,
        "links": _links_script,
        "structured": _structured_script,
        "playwright": _playwright_script,
        "crawl4ai": _crawl4ai_script,
        "document": _document_script,
    }
    builder = builders.get(engine, _table_script)
    body, deps = builder(url, dataset, pagination, max_pages, delay)

    # Only import what the generated body actually uses.
    stdlib = [name for name in ("os", "time") if f"{name}." in body]
    head = HEADER.format(
        version=version,
        url=url,
        engine=engine,
        created=created,
        deps=" ".join(deps),
        stdlib_imports="\n" + "\n".join(f"import {name}" for name in stdlib) + "\n"
        if stdlib
        else "",
    )
    return head + _insert_rate_limit(body, delay)


# --------------------------------------------------------------------------- scripts
def _json_api_script(url, dataset, pagination, max_pages, delay) -> tuple[str, list[str]]:
    api_url = dataset.get("api_url") or url
    records_path = dataset.get("records_path")
    template = pagination.get("url_template")
    ptype = pagination.get("type", "none")

    walk = ""
    if records_path:
        walk = f'''
def walk(payload, path="{records_path}"):
    node = payload
    for part in path.split("."):
        if not part:
            continue
        if isinstance(node, dict):
            node = node.get(part)
        else:
            return []
    return node or []
'''
    else:
        walk = """
def walk(payload, path=None):
    if isinstance(payload, list):
        return payload
    if isinstance(payload, dict):
        for value in payload.values():
            if isinstance(value, list) and value and isinstance(value[0], dict):
                return value
    return []
"""

    if ptype == "page_number" and template:
        loop = f'''
URL_TEMPLATE = "{template}"
MAX_PAGES = {max_pages}

rows = []
with httpx.Client(headers=HEADERS, timeout=30.0, follow_redirects=True) as client:
    for page in range({pagination.get("start", 1)}, {pagination.get("start", 1)} + MAX_PAGES):
        response = client.get(URL_TEMPLATE.replace("{{page}}", str(page)))
        response.raise_for_status()
        batch = walk(response.json())
        if not batch:
            break
        rows.extend(batch)
        time.sleep(REQUEST_DELAY_SECONDS)
'''
    else:
        loop = f'''
API_URL = "{api_url}"

rows = []
with httpx.Client(headers=HEADERS, timeout=30.0, follow_redirects=True) as client:
    response = client.get(API_URL)
    response.raise_for_status()
    rows = walk(response.json())
'''

    body = f"""import httpx
import pandas as pd

HEADERS = {{"User-Agent": "research-reproduction-script"}}
{walk}{loop}
df = pd.json_normalize(rows)
print(df.shape)
df.to_csv("dataset.csv", index=False)
"""
    return body, ["httpx", "pandas"]


def _table_script(url, dataset, pagination, max_pages, delay) -> tuple[str, list[str]]:
    index = dataset.get("table_index") or 0
    template = pagination.get("url_template")
    if template and max_pages > 1:
        loop = f'''
URL_TEMPLATE = "{template}"
MAX_PAGES = {max_pages}

frames = []
with httpx.Client(headers=HEADERS, timeout=30.0, follow_redirects=True) as client:
    for page in range({pagination.get("start", 1)}, {pagination.get("start", 1)} + MAX_PAGES):
        response = client.get(URL_TEMPLATE.replace("{{page}}", str(page)))
        response.raise_for_status()
        tables = pd.read_html(io.StringIO(response.text), flavor="lxml")
        if len(tables) <= TABLE_INDEX:
            break
        frames.append(tables[TABLE_INDEX])
        time.sleep(REQUEST_DELAY_SECONDS)

df = pd.concat(frames, ignore_index=True)
'''
    else:
        loop = f'''
SOURCE_URL = "{url}"

with httpx.Client(headers=HEADERS, timeout=30.0, follow_redirects=True) as client:
    response = client.get(SOURCE_URL)
    response.raise_for_status()

df = pd.read_html(io.StringIO(response.text), flavor="lxml")[TABLE_INDEX]
'''
    body = f"""import io

import httpx
import pandas as pd

HEADERS = {{"User-Agent": "research-reproduction-script"}}
TABLE_INDEX = {index}
{loop}
print(df.shape)
df.to_csv("dataset.csv", index=False)
"""
    return body, ["httpx", "pandas", "lxml"]


def _repeated_script(url, dataset, pagination, max_pages, delay) -> tuple[str, list[str]]:
    selector = dataset.get("selector") or "div"
    template = pagination.get("url_template")
    pages_block = (
        f'''URL_TEMPLATE = "{template}"
PAGES = [URL_TEMPLATE.replace("{{page}}", str(p)) for p in range({pagination.get("start", 1)}, {pagination.get("start", 1)} + {max_pages})]'''
        if template and max_pages > 1
        else f'PAGES = ["{url}"]'
    )
    body = f'''import httpx
import pandas as pd
from lxml import html as lxml_html
from urllib.parse import urljoin

HEADERS = {{"User-Agent": "research-reproduction-script"}}
ITEM_SELECTOR = "{selector}"
{pages_block}


def parse_item(node, base_url):
    row = {{}}
    heading = node.cssselect("h1, h2, h3, h4, h5")
    if heading:
        row["title"] = " ".join(heading[0].text_content().split())
    link = node.cssselect("a[href]")
    if link:
        row["link"] = urljoin(base_url, link[0].get("href"))
    time_node = node.cssselect("time")
    if time_node:
        row["date"] = time_node[0].get("datetime") or time_node[0].text_content().strip()
    if not row:
        row["text"] = " ".join(node.text_content().split())[:400]
    return row


rows = []
with httpx.Client(headers=HEADERS, timeout=30.0, follow_redirects=True) as client:
    for page_url in PAGES:
        response = client.get(page_url)
        response.raise_for_status()
        tree = lxml_html.fromstring(response.text)
        items = tree.cssselect(ITEM_SELECTOR)
        if not items:
            break
        rows.extend(parse_item(item, page_url) for item in items)
        time.sleep(REQUEST_DELAY_SECONDS)

df = pd.DataFrame(rows)
print(df.shape)
df.to_csv("dataset.csv", index=False)
'''
    return body, ["httpx", "pandas", "lxml", "cssselect"]


def _file_script(url, dataset, pagination, max_pages, delay) -> tuple[str, list[str]]:
    target = dataset.get("api_url") or url
    body = f'''import io

import httpx
import pandas as pd

FILE_URL = "{target}"
HEADERS = {{"User-Agent": "research-reproduction-script"}}

with httpx.Client(headers=HEADERS, timeout=60.0, follow_redirects=True) as client:
    response = client.get(FILE_URL)
    response.raise_for_status()

buffer = io.BytesIO(response.content)
if FILE_URL.endswith((".xlsx", ".xls")):
    df = pd.read_excel(buffer)
elif FILE_URL.endswith(".parquet"):
    df = pd.read_parquet(buffer)
elif FILE_URL.endswith((".json", ".jsonl")):
    df = pd.read_json(buffer, lines=FILE_URL.endswith(".jsonl"))
else:
    df = pd.read_csv(buffer, sep=None, engine="python")

print(df.shape)
df.to_csv("dataset.csv", index=False)
'''
    return body, ["httpx", "pandas"]


def _article_script(url, dataset, pagination, max_pages, delay) -> tuple[str, list[str]]:
    body = f'''import json

import httpx
import pandas as pd
import trafilatura

SOURCE_URL = "{url}"
HEADERS = {{"User-Agent": "research-reproduction-script"}}

with httpx.Client(headers=HEADERS, timeout=30.0, follow_redirects=True) as client:
    response = client.get(SOURCE_URL)
    response.raise_for_status()

payload = trafilatura.extract(
    response.text, url=SOURCE_URL, output_format="json", with_metadata=True
)
record = json.loads(payload) if payload else {{}}
df = pd.DataFrame([record])
print(df.shape)
df.to_csv("dataset.csv", index=False)
'''
    return body, ["httpx", "pandas", "trafilatura"]


def _feed_script(url, dataset, pagination, max_pages, delay) -> tuple[str, list[str]]:
    body = f'''import feedparser
import pandas as pd

FEED_URL = "{url}"

parsed = feedparser.parse(FEED_URL)
df = pd.DataFrame(
    [
        {{
            "title": entry.get("title", ""),
            "link": entry.get("link", ""),
            "published": entry.get("published", entry.get("updated", "")),
            "summary": entry.get("summary", ""),
        }}
        for entry in parsed.entries
    ]
)
print(df.shape)
df.to_csv("dataset.csv", index=False)
'''
    return body, ["feedparser", "pandas"]


def _links_script(url, dataset, pagination, max_pages, delay) -> tuple[str, list[str]]:
    body = f'''from urllib.parse import urljoin

import httpx
import pandas as pd
from lxml import html as lxml_html

SOURCE_URL = "{url}"
HEADERS = {{"User-Agent": "research-reproduction-script"}}

with httpx.Client(headers=HEADERS, timeout=30.0, follow_redirects=True) as client:
    response = client.get(SOURCE_URL)
    response.raise_for_status()

tree = lxml_html.fromstring(response.text)
rows = [
    {{"url": urljoin(SOURCE_URL, a.get("href")), "text": " ".join(a.text_content().split())}}
    for a in tree.xpath("//a[@href]")
]
df = pd.DataFrame(rows).drop_duplicates(subset=["url"])
print(df.shape)
df.to_csv("dataset.csv", index=False)
'''
    return body, ["httpx", "pandas", "lxml"]


def _structured_script(url, dataset, pagination, max_pages, delay) -> tuple[str, list[str]]:
    body = f'''import json

import httpx
import pandas as pd
from lxml import html as lxml_html

SOURCE_URL = "{url}"
HEADERS = {{"User-Agent": "research-reproduction-script"}}

with httpx.Client(headers=HEADERS, timeout=30.0, follow_redirects=True) as client:
    response = client.get(SOURCE_URL)
    response.raise_for_status()

tree = lxml_html.fromstring(response.text)
records = []
for script in tree.xpath("//script[@type='application/ld+json']"):
    try:
        data = json.loads(script.text_content())
    except Exception:
        continue
    records.extend(data if isinstance(data, list) else [data])

df = pd.json_normalize(records)
print(df.shape)
df.to_csv("dataset.csv", index=False)
'''
    return body, ["httpx", "pandas", "lxml"]


def _playwright_script(url, dataset, pagination, max_pages, delay) -> tuple[str, list[str]]:
    selector = dataset.get("selector")
    table_index = dataset.get("table_index")
    extraction = (
        f"""    tables = pd.read_html(io.StringIO(html), flavor="lxml")
    df = tables[{table_index or 0}]"""
        if table_index is not None or not selector
        else f'''    tree = lxml_html.fromstring(html)
    rows = []
    for node in tree.cssselect("{selector}"):
        heading = node.cssselect("h1, h2, h3, h4, h5")
        link = node.cssselect("a[href]")
        rows.append(
            {{
                "title": " ".join(heading[0].text_content().split()) if heading else None,
                "link": urljoin(SOURCE_URL, link[0].get("href")) if link else None,
                "text": " ".join(node.text_content().split())[:400],
            }}
        )
    df = pd.DataFrame(rows)'''
    )
    body = f'''import io
from urllib.parse import urljoin

import pandas as pd
from lxml import html as lxml_html
from playwright.sync_api import sync_playwright

SOURCE_URL = "{url}"
WAIT_FOR = {repr(dataset.get("wait_for"))}

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page(user_agent="research-reproduction-script")
    page.goto(SOURCE_URL, wait_until="domcontentloaded", timeout=45000)
    page.wait_for_load_state("networkidle", timeout=15000)
    if WAIT_FOR:
        page.wait_for_selector(WAIT_FOR, timeout=15000)
    html = page.content()
    browser.close()

{extraction}
print(df.shape)
df.to_csv("dataset.csv", index=False)
'''
    return body, ["playwright", "pandas", "lxml", "cssselect"]


def _crawl4ai_script(url, dataset, pagination, max_pages, delay) -> tuple[str, list[str]]:
    body = f'''import asyncio
import io

import pandas as pd
from crawl4ai import AsyncWebCrawler

SOURCE_URL = "{url}"


async def main():
    async with AsyncWebCrawler(verbose=False) as crawler:
        result = await crawler.arun(url=SOURCE_URL)
    html = getattr(result, "cleaned_html", "") or getattr(result, "html", "")
    tables = pd.read_html(io.StringIO(html), flavor="lxml")
    df = tables[0] if tables else pd.DataFrame([{{"markdown": str(result.markdown)}}])
    print(df.shape)
    df.to_csv("dataset.csv", index=False)


asyncio.run(main())
'''
    return body, ["crawl4ai", "pandas", "lxml"]


def _document_script(url, dataset, pagination, max_pages, delay) -> tuple[str, list[str]]:
    body = f'''import httpx
import pandas as pd
import fitz  # PyMuPDF

DOCUMENT_URL = "{url}"
HEADERS = {{"User-Agent": "research-reproduction-script"}}

with httpx.Client(headers=HEADERS, timeout=60.0, follow_redirects=True) as client:
    response = client.get(DOCUMENT_URL)
    response.raise_for_status()

rows = []
with fitz.open(stream=response.content, filetype="pdf") as document:
    for index in range(document.page_count):
        page = document.load_page(index)
        rows.append({{"page": index + 1, "text": page.get_text("text")}})

df = pd.DataFrame(rows)
print(df.shape)
df.to_csv("dataset.csv", index=False)
'''
    return body, ["httpx", "pandas", "pymupdf"]
