"""Reproduction README and research bundle (spec sections 34, 78).

The bundle is what a researcher attaches to a paper: dataset, dictionary,
provenance, recipe, reproducer script and a quality summary.
"""

from __future__ import annotations

import io
import json
import zipfile
from datetime import UTC, datetime
from typing import Any

import pandas as pd

from ..config import APP_AUTHOR, APP_AUTHOR_URL, APP_VERSION
from ..models import Provenance, QualityReport


def reproduction_readme(
    *,
    recipe: dict[str, Any],
    provenance: Provenance,
    quality: QualityReport | None,
    dependencies: list[str],
) -> str:
    """Markdown README explaining how to reproduce the dataset."""
    lines = [
        f"# Reproduction package — {recipe.get('name', 'dataset')}",
        "",
        f"Generated by Smart Research Web Scraper {APP_VERSION} on "
        f"{datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}.",
        f"Developed by {APP_AUTHOR} ({APP_AUTHOR_URL}).",
        "",
        "## Source",
        "",
        f"- Source URL: {provenance.source_url}",
        f"- Final URL: {provenance.final_url}",
        f"- Retrieved at: {provenance.retrieved_at.isoformat()}",
        f"- Extraction method: {provenance.engine}",
        f"- Why this method: {provenance.route_rationale}",
        f"- robots.txt status: {provenance.robots_status}",
        f"- User agent: {provenance.user_agent}",
        "",
        "## Dataset",
        "",
        f"- Rows extracted: {provenance.rows_raw:,}",
        f"- Rows after cleaning: {provenance.rows_clean:,}",
        f"- Columns: {len(provenance.columns)}",
        f"- Pages requested / successful: {provenance.pages_requested} / {provenance.pages_successful}",
        f"- Recipe hash: `{provenance.recipe_hash}`",
        "",
    ]

    if quality is not None:
        lines += [
            "## Quality summary",
            "",
            f"- Missing cells: {quality.missing_cells:,} ({quality.missing_pct}%)",
            f"- Duplicate rows: {quality.duplicate_rows:,}",
        ]
        if quality.constant_columns:
            lines.append(f"- Constant columns: {', '.join(quality.constant_columns[:8])}")
        if quality.conversion_failures:
            lines.append(
                "- Conversion failures: "
                + ", ".join(f"{k} ({v})" for k, v in list(quality.conversion_failures.items())[:8])
            )
        if quality.schema_drift:
            lines.append("- Schema drift: " + "; ".join(quality.schema_drift[:4]))
        lines.append("")

    if provenance.cleaning_operations:
        lines += ["## Cleaning operations applied", ""]
        for operation in provenance.cleaning_operations:
            lines.append(
                f"- {operation.get('operation')}: {operation.get('changed_cells', 0)} cells changed"
                + (
                    f", {operation['conversion_failures']} conversion failures"
                    if operation.get("conversion_failures")
                    else ""
                )
            )
        lines.append("")

    lines += [
        "## Files in this package",
        "",
        "| File | Description |",
        "| --- | --- |",
        "| `dataset_clean.csv` | The analysis-ready dataset |",
        "| `dataset_raw.csv` | The dataset exactly as extracted, before cleaning |",
        "| `data_dictionary.csv` | Variable labels, types, missingness, name provenance |",
        "| `provenance.json` | Full run manifest |",
        "| `extraction_recipe.json` / `.yaml` | Machine-readable description of the extraction |",
        "| `generated_scraper.py` | Standalone script that reproduces the extraction |",
        "| `quality_summary.csv` | Per-column quality metrics |",
        "",
        "## Reproducing",
        "",
        "```bash",
        f"pip install {' '.join(dependencies)}",
        "python generated_scraper.py",
        "```",
        "",
        "The script contains no credentials. If the source needs authorisation, supply it through",
        "environment variables and make sure you are permitted to access the data.",
        "",
        "## Notes on responsible use",
        "",
        "- robots.txt status at collection time is recorded above.",
        "- Check the source terms of use, licence and any personal-data restrictions before",
        "  redistributing the dataset.",
        "- Cite the original data publisher, not only this tool.",
        "",
    ]
    return "\n".join(lines)


def citation_text(provenance: Provenance, title: str = "Dataset") -> str:
    """A ready-to-paste citation line for the dataset (spec section 85)."""
    date = provenance.retrieved_at.strftime("%Y, %B %d")
    return (
        f"{title} [Data set]. Retrieved {date} from {provenance.final_url} "
        f"using Smart Research Web Scraper {provenance.app_version} by {APP_AUTHOR} "
        f"({APP_AUTHOR_URL}) — method: {provenance.engine}; recipe {provenance.recipe_hash}."
    )


def build_bundle(
    *,
    clean_df: pd.DataFrame,
    raw_df: pd.DataFrame | None,
    dictionary: pd.DataFrame | None,
    provenance: Provenance,
    recipe: dict[str, Any],
    recipe_yaml: bytes,
    script: str,
    quality: QualityReport | None,
    include_raw: bool = True,
) -> bytes:
    """Build the research ZIP bundle in memory."""
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("dataset_clean.csv", clean_df.to_csv(index=False))
        if include_raw and raw_df is not None:
            archive.writestr("dataset_raw.csv", raw_df.to_csv(index=False))
        if dictionary is not None:
            archive.writestr("data_dictionary.csv", dictionary.to_csv(index=False))
        archive.writestr(
            "provenance.json",
            json.dumps(json.loads(provenance.model_dump_json()), indent=2, ensure_ascii=False),
        )
        archive.writestr("extraction_recipe.json", json.dumps(recipe, indent=2, ensure_ascii=False))
        archive.writestr("extraction_recipe.yaml", recipe_yaml.decode("utf-8"))
        archive.writestr("generated_scraper.py", script)
        if quality is not None:
            archive.writestr(
                "quality_summary.csv", pd.DataFrame(quality.column_stats).to_csv(index=False)
            )
        archive.writestr(
            "README_reproduction.md",
            reproduction_readme(
                recipe=recipe,
                provenance=provenance,
                quality=quality,
                dependencies=["httpx", "pandas", "lxml"],
            ),
        )
        archive.writestr("CITATION.txt", citation_text(provenance, recipe.get("name", "Dataset")))
    return buffer.getvalue()
