"""Generate `requirements.txt` from `uv.lock` (audit v0.2 sections 43-46).

The repository used to carry two independent dependency manifests: a lockfile
with exact versions, and a hand-written `requirements.txt` with none. They could
disagree, and on Streamlit Community Cloud — which reads `uv.lock` first — the
file a reader would naturally inspect was not the file being installed.

There is now one source of truth. `uv.lock` resolves the dependencies, and this
script exports the default (non-optional) group from it. Whichever manifest a
platform picks, the installed versions are identical.

    python scripts/sync_requirements.py           # rewrite requirements.txt
    python scripts/sync_requirements.py --check   # fail if it is out of date
"""

from __future__ import annotations

import argparse
import shutil
import subprocess  # noqa: S404 - fixed argv, no shell
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "requirements.txt"

HEADER = """\
# Smart Research Web Scraper — core dependencies.
#
# GENERATED FILE — do not edit by hand.
# Source of truth: uv.lock. Regenerate with:
#
#     python scripts/sync_requirements.py
#
# Why it is generated: Streamlit Community Cloud reads uv.lock before it reads
# this file, so an independently maintained requirements.txt could describe an
# environment that is never actually installed. Exporting it from the lockfile
# means both paths install byte-identical versions, which is what makes a run
# reproducible months later.
#
# This is the DEFAULT group only. Optional engines are deliberately absent; the
# application runs fully without them and reports them honestly in
# Settings -> Engines & keys:
#   playwright   browser rendering + network API discovery   (Apache-2.0)
#   crawl4ai     local adaptive engine                       (Apache-2.0)
#   firecrawl-py hosted extraction, needs FIRECRAWL_API_KEY   (MIT)
#   kaleido      export charts as PNG/SVG/PDF                 (MIT)
#   pymupdf      PDF/document extraction                      (AGPL-3.0)
#   pyreadr      R .rds export                                (AGPL-3.0)
#
# Install those with the extras instead, e.g.  pip install -e ".[browser]"
# See THIRD_PARTY_LICENSES.md for the licence of every package.
"""

EXPORT_ARGS = [
    "export",
    "--no-hashes",
    "--no-dev",
    "--no-emit-project",
    "--format",
    "requirements-txt",
]


def export() -> str:
    """Ask uv for the locked default dependency group."""
    uv = shutil.which("uv")
    if not uv:
        raise SystemExit(
            "uv is not installed. Install it from https://docs.astral.sh/uv/ "
            "and re-run this script."
        )

    completed = subprocess.run(  # noqa: S603 - argv is fixed above, shell=False
        [uv, *EXPORT_ARGS],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        raise SystemExit(f"uv export failed:\n{completed.stderr.strip()}")

    body = "\n".join(
        line
        for line in completed.stdout.splitlines()
        # Drop uv's own "autogenerated by" banner; this file has its own header.
        if not line.startswith("# This file was autogenerated")
        and not line.startswith("#    uv export")
    ).strip()

    return f"{HEADER}\n{body}\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if requirements.txt differs from the lockfile.",
    )
    args = parser.parse_args()

    generated = export()
    current = TARGET.read_text(encoding="utf-8").replace("\r\n", "\n") if TARGET.exists() else ""

    if args.check:
        if current != generated:
            print(
                "requirements.txt is out of date with uv.lock.\n"
                "Run: python scripts/sync_requirements.py",
                file=sys.stderr,
            )
            return 1
        print("requirements.txt matches uv.lock.")
        return 0

    if current == generated:
        print("requirements.txt already matches uv.lock.")
        return 0

    TARGET.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Wrote {TARGET.relative_to(ROOT)} ({len(generated.splitlines())} lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
